on: [workflow_call]

jobs:
  tests-coverage:
    name: Build code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          standalone: true
          run_install: true

      - name: Create code coverage
        run: pnpm run test:coverage
        env:
          CI: true

      - name: Store code coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage
