on: [workflow_call]

jobs:
  tests-coverage:
    name: Build code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm, node and dependencies
        uses: pnpm/setup@v1
        with:
          runtime: node@24

      - name: Create code coverage
        run: pnpm run test:coverage
        env:
          CI: true

      - name: Store code coverage
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage
          path: coverage
